apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-python
  namespace: demo-devops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: demo-devops.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-devops-python
                port:
                  number: 80
